import type { Metadata } from "next";
import { Gabarito, Geist_Mono } from "next/font/google";
import { SideNav } from "@/components/nav";
import "./globals.css";

const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${gabarito.variable} ${geistMono.variable} h-full`}>
      <body className="min-h-full font-sans antialiased">
        <div className="app-shell min-h-dvh">
          <SideNav />
          <main className="app-content grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
